### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by LapinFou** [clamy54/docker-svn-iF.SVNAdmin#5]
At first, an happy new year. I wish you all the best.

With the latest version, my docker is restarting in an infinite loop. 😓

```
***** Container starting at 18:20:59 - 2025-01-06 *****
Setting up timezone to Europe/Paris
Current default time zone: 'Europe/Paris'
Local time is now:      Mon Jan  6 18:21:00 CET 2025.
Universal Time is now:  Mon Jan  6 17:21:00 UTC 2025.
Setting-up apache2 ...
Setting-up apache2-ssl for self-signed certificate
Setting up default python interpreter
Starting apache2 ...
[Mon Jan 06 18:21:01.039661 2025] [:crit] [pid 32:tid 32] (38)Function not implemented: AH00141: Could not initialize random number generator

***** Container starting at 18:21:57 - 2025-01-06 *****
Setting up timezone to Europe/Paris
Current default time zone: 'Europe/Paris'
Local time is now:      Mon Jan  6 18:21:57 CET 2025.
Universal Time is now:  Mon Jan  6 17:21:57 UTC 2025.
Setting-up apache2 ...
Setting-up apache2-ssl for self-signed certificate
Setting up default python interpreter
Starting apache2 ...
[Mon Jan 06 18:21:58.028597 2025] [:crit] [pid 32:tid 32] (38)Function not implemented: AH00141: Could not initialize random number generator
```

It seems some new dependencies are now required with this latest apache2 version. Those dependencies seems not available on DSM 7 Synology NAS. 😣

**Comment by clamy54** [comment]
Hi,

I cannot reproduce the issue. My Synology is running DSM 7.2.2-72806 Update 2 and the container (the ubuntu2404 version) is running fine.
 
What's your version of DSM ? What env settings are you using ?

**Comment by LapinFou** [comment]
Sorry for the missing details.

My syno is an old **DS916+** (INTEL Pentium N3710) with 8GB of RAM.
DSM version is **DSM 7.2.2-72806 Update 2**

I'm using Portainer for maintaining my dockers.
The docker compose settings:
```
version: "3.8"
services:
  svnadmin :
    image: clamy54/svn-svnadmin:latest
    hostname: svnadmin
    container_name: svnadmin
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/svnadmin/hooks:/var/hooks
      - /volume1/docker/svnadmin/svn:/var/svn
      - /volume1/docker/svnadmin/apache2/keys:/etc/apache2/keys
      - /volume1/docker/svnadmin/apache2/dav_svn:/etc/apache2/dav_svn
    ports:
      - 8082:80
      - 8083:443
    restart: unless-stopped
```

The Env settings (_stack.env_ file):
```
TZ=Europe/Paris
DEFAULT_PYTHON=2
```
